name: inductor-CPU-perf-nightly

on:
  schedule:
    - cron: 0 7 * * 1-6
    - cron: 0 7 * * 0
  workflow_dispatch:
    inputs:
      training:
        description: Run training (off by default)?
        required: false
        type: boolean
        default: false
      inference:
        description: Run inference (on by default)?
        required: false
        type: boolean
        default: true
      inductor_cpu:
        description: Run inductor_cpu?
        required: false
        type: boolean
        default: true
      benchmark_configs:
        description: The list of configs used the benchmark
        required: false
        type: string
        default: inductor_huggingface_perf,inductor_timm_perf,inductor_torchbench_perf

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  linux-focal-cpu-py3_8-gcc9-inductor-build:
    name: cpu-py3.8-gcc9
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-focal-cpu-py3.8-gcc9
      docker-image-name: pytorch-linux-focal-py3.8-gcc9
      test-matrix: |
        { include: [
          { config: "inductor_huggingface_perf", shard: 1, num_shards: 3, runner: "linux.24xl.spr-metal" },
          { config: "inductor_huggingface_perf", shard: 2, num_shards: 3, runner: "linux.24xl.spr-metal" },
          { config: "inductor_huggingface_perf", shard: 3, num_shards: 3, runner: "linux.24xl.spr-metal" },
          { config: "inductor_timm_perf", shard: 1, num_shards: 5, runner: "linux.24xl.spr-metal" },
          { config: "inductor_timm_perf", shard: 2, num_shards: 5, runner: "linux.24xl.spr-metal" },
          { config: "inductor_timm_perf", shard: 3, num_shards: 5, runner: "linux.24xl.spr-metal" },
          { config: "inductor_timm_perf", shard: 4, num_shards: 5, runner: "linux.24xl.spr-metal" },
          { config: "inductor_timm_perf", shard: 5, num_shards: 5, runner: "linux.24xl.spr-metal" },
          { config: "inductor_torchbench_perf", shard: 1, num_shards: 4, runner: "linux.24xl.spr-metal" },
          { config: "inductor_torchbench_perf", shard: 2, num_shards: 4, runner: "linux.24xl.spr-metal" },
          { config: "inductor_torchbench_perf", shard: 3, num_shards: 4, runner: "linux.24xl.spr-metal" },
          { config: "inductor_torchbench_perf", shard: 4, num_shards: 4, runner: "linux.24xl.spr-metal" },
        ]}
      selected-test-configs: ${{ inputs.benchmark_configs }}
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

  linux-focal-cpu-py3_8-gcc9-inductor-test-nightly:
    name: cpu-py3.8-gcc9
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-focal-cpu-py3_8-gcc9-inductor-build
    if: github.event.schedule == '0 7 * * 1-6'
    with:
      build-environment: linux-focal-cpu-py3.8-gcc9
      dashboard-tag: training-false-inference-true-inductor_cpu-true
      docker-image: ${{ needs.linux-focal-cpu-py3_8-gcc9-inductor-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-cpu-py3_8-gcc9-inductor-build.outputs.test-matrix }}
      use-gha: anything-non-empty-to-use-gha
      timeout-minutes: 720
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
